### ISSUE TITLE
Hyperlink not working

### ISSUE THREAD

**Issue by himanshu007-creator** [girlscript/GirlScript-Summer-of-Code#1]
![2021-02-01](https://user-images.githubusercontent.com/65963997/106478100-e2708e80-64ce-11eb-9da7-04f66a660420.png)

this "ADD YOUR PROJECT" is not working. i checked the code. hyperlink reference in correct, but still its not functional

**Comment by himanshu007-creator** [comment]
Please have a look here https://github.com/girlscript/GirlScript-Summer-of-Code/pull/2

**Comment by priyanshisharma** [comment]
Resolved in #2 , so closing this
