### ISSUE TITLE
Alignment needed: Sponsor section

### ISSUE THREAD

**Issue by JoshuaPoddoku** [girlscript/GirlScript-Summer-of-Code#26]
My Screen display has 1980x1080 resolution

![image](https://user-images.githubusercontent.com/31725457/106876185-7889fc00-66fd-11eb-9e44-06c96bd91232.png)

**Comment by chait04** [comment]
On my screen, everything working good
![Screenshot (70)](https://user-images.githubusercontent.com/59140343/108347136-320cc500-7206-11eb-8643-9ad4bba2d091.png)

**Comment by Vishal-raj-1** [comment]
@JoshuaPoddoku Check it again, If everything is fine then close this issue !!

**Comment by JoshuaPoddoku** [comment]
Yes, seems to be fine now
