### ISSUE TITLE
Typo  on Schedule Page

### ISSUE THREAD

**Issue by Abhayraj1707** [girlscript/GirlScript-Summer-of-Code#27]
Typo error on Schedule Page. I think this "enthusisats cans tart " text is to be replaced with "enthusiasts can start". (screenshot attached below)

Concerning File
`schedule.html`

#Screenshot
![error](https://user-images.githubusercontent.com/62218504/107068290-6e075980-6806-11eb-8310-333906075455.jpeg)

**Comment by priyanshisharma** [comment]
Resolved in #28 so closing this
