### ISSUE TITLE
Project HotelOnTouch is not listed in 2021 projects in website

### ISSUE THREAD

**Issue by ayan-biswas0412** [girlscript/GirlScript-Summer-of-Code#36]
I got a email that my project https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch is selected but still in the website it is not updated can anybody help me about this , or I have to make edit and make a PR to enlist myself ? Any type of suggestions will be helpful , Thanking you all in advance

**Comment by ayan-biswas0412** [comment]
@weebo-ary can you please tell what happened to other projects ? I got an email about the acceptance of my project but still it is not there in the official website

**Comment by weebo-ary** [comment]
Hey @ayan-biswas0412,
We have your project and we are uploading the projects on the site in a subsequent manner.....and your project will be deployed soon on the website.
Thank you

**Comment by ayan-biswas0412** [comment]
@weebo-ary thanks for the information
