### ISSUE TITLE
Rocket Icon in Schedule Section is showing very large in Safari Browser.

### ISSUE THREAD

**Issue by encodeArnab** [girlscript/GirlScript-Summer-of-Code#37]
large icon error on Home Page. The size of the rocket icon svg is showing very large in safari Browser   
(screenshot attached below)

Concerning File
`index.html`

#Screenshot
<img width="800" alt="Screenshot 2021-02-13 at 3 27 02 AM" src="https://user-images.githubusercontent.com/77114532/107826733-623e0900-6dab-11eb-9e0a-ad4b45ec776f.png">

**Comment by encodeArnab** [comment]
I sent a pull request regarding this issue.

**Comment by priyanshisharma** [comment]
Fixed in #38 so closing this.
