### ISSUE TITLE
carousel should have timer to change current frame

### ISSUE THREAD

**Issue by chait04** [girlscript/GirlScript-Summer-of-Code#49]
<strong>Feature request</strong>

In the rewards section, the images should change after few seconds...

<code> and also in console it is saying use latest version on jquery </code>

![Screenshot (68)](https://user-images.githubusercontent.com/59140343/108346379-5320e600-7205-11eb-88c7-1e575bdec81c.png)

**Comment by nishihere19** [comment]
I think it has a timer and images are changing automatically within few seconds.

**Comment by chait04** [comment]
oh, it's working now, I think when we change slides manually after that is doesn't restart the timer... if this behavior is fine then we can close this issue 👍🏿
