### ISSUE TITLE
Typo error on Schedule Page

### ISSUE THREAD

**Issue by tusharjain0022** [girlscript/GirlScript-Summer-of-Code#5]
### Description 
Typo error on Schedule Page. I guess this "someone famous" text left to be replaced with "GSSOC'21". (screenshot attached below)

### Concerning File
`schedule.html`

### Screenshot
![Screenshot (267)_LI](https://user-images.githubusercontent.com/59157988/106565481-ba3f5a80-64e3-11eb-8f99-9fe6ed79908d.jpg)

**Comment by priyanshisharma** [comment]
Resolved in #6 so closing this.
