### ISSUE TITLE
Update links for "Kidney Exchange" project

### ISSUE THREAD

**Issue by siv2r** [girlscript/GirlScript-Summer-of-Code#64]
Please update the following links on the GSSoC'21 project page.

Kidney Exchange: [GSSoC'21 project page](https://gssoc.girlscript.tech/projects.html)

**Changes Needed**
1. Slack group: [link](https://join.slack.com/t/kidney-exchange/shared_invite/zt-n54e89o7-yB5E6eZl7q3DAvLFdUAwgA)
2. Demo video: [link](https://drive.google.com/file/d/1Wp6K0wRsPjxwvTWzIIVIQMqYhe1ZMX_0/view?usp=sharing)

**Comment by praveenscience** [comment]
@siv2r Just go ahead and create a PR. 😊

**Comment by siv2r** [comment]
This issue has been resolved!
