### ISSUE TITLE
[GSSoC'21] Matching Github links of two different projects in Gssoc website under project

### ISSUE THREAD

**Issue by ArchishmanSengupta** [girlscript/GirlScript-Summer-of-Code#84]
![issue](https://user-images.githubusercontent.com/71402528/110495033-2122e580-811a-11eb-92d3-3218f4aefb92.png)

Above projects have the same links.  Kindly check.

**Comment by ravikr126** [comment]
can I work on this?

**Comment by chait04** [comment]
Its working fine for me....

**Comment by ArunTeltia** [comment]
I dont think its an issue now, @ArchishmanSengupta you can close this

**Comment by ArchishmanSengupta** [comment]
sure @ArunTeltia
